export const SUBAGENT_PROMPT = [
  'Use `<task>` to spawn a subagent for parallel exploration or specialized work.',
  '',
  'Format:',
  '<task type="explore">Search the codebase for authentication-related files and patterns</task>',
  '<task type="general">Analyze the test coverage and identify gaps</task>',
  '',
  'Agent types:',
  '- `explore`: Read-only codebase search (grep, glob). Fast and safe.',
  '- `general`: Full capabilities. Use for independent multi-step work.',
  '',
  'When to use subagents:',
  '- Broad codebase exploration before making changes',
  '- Searching for patterns across many files',
  '- Tasks that can run independently of your current work',
  '',
  'Do NOT use subagents for:',
  '- Simple single-file operations (just use `<read>` or `<grep>` directly)',
  '- Tasks that require your current conversation context',
].join('\n');
