/**
 * Filesystem Plugin - Prompt contribution
 */

/* eslint-disable no-template-curly-in-string */
export const FILESYSTEM_PROMPT = [
  '## Read — `<read path="file.ts"/>` `<read path="file.ts" offset="100" limit="50"/>`',
  'Always read before editing. Output format:',
  '```',
  '[typescript] src/app.ts',
  '1│import { foo } from "./foo";',
  '2│export class App {',
  '3│  run() { foo(); }',
  '4│}',
  '```',
  'The header tells you the language and path. Each line is `number│content` — the `│` separates the line number from the actual code, preserving its exact indentation. Use these numbers as `startLine` in your `<edit>` hunks.',
  '',
  '## Edit — Unified diff format. You MUST `<read>` the file first.',
  '',
  'Each `<edit>` block targets one file. Inside it, write one or more **hunks**, each starting with a hunk header:',
  '`@@ -startLine,count @@`',
  '- **startLine** (1-based): the first line number this hunk touches, as shown by `<read>`.',
  '- **count**: how many *existing* lines this hunk covers (context lines + removed lines). Set count=0 for a pure insertion.',
  '',
  'After the header, every line MUST begin with exactly one of these prefixes:',
  '- ` ` (space) — context line, kept unchanged. Must match the file verbatim.',
  '- `-` — line to remove.',
  '- `+` — line to add.',
  '',
  'You may include multiple hunks in a single `<edit>` block. They are applied top-down.',
  '',
  '```',
  '<edit path="src/app.ts">',
  '@@ -5,1 @@',
  '-import { old } from "./old";',
  '+import { replacement } from "./new";',
  '@@ -15,3 @@',
  '-  const name = "old";',
  '-  const value = 42;',
  '-  return { name, value };',
  '+  const name = "new";',
  '+  const value = 100;',
  '+  return { name, value, extra: true };',
  '</edit>',
  '```',
  '',
  '## Write — `<write path="src/file.ts">content</write>`',
] as const;
