/**
 * Filesystem Plugin - Prompt contribution
 */

/* eslint-disable no-template-curly-in-string */
export const FILESYSTEM_PROMPT = [
  '## Read — `<read path="file.ts"/>` `<read path="file.ts" offset="100" limit="50"/>`',
  'ALWAYS read a file before editing it. Output format:',
  '```',
  '[typescript] src/app.ts',
  '   1│import { foo } from "./foo";',
  '   2│export class App {',
  '   3│  run() { foo(); }',
  '   4│}',
  '```',
  'The number before `│` is the **line number**. The content after `│` is the exact code with its original indentation. Use these line numbers as `startLine` in `<edit>` hunks.',
  '',
  '## Edit — Unified diff format. You MUST `<read>` the file first.',
  '',
  'Format: `<edit path="file.ts">` with one or more hunks.',
  '',
  '### Hunk header: `@@ -startLine,count @@`',
  '- `startLine`: the **exact line number** from `<read>` output where this hunk begins. Do NOT guess or calculate — copy from `<read>` output.',
  '- `count`: number of existing lines this hunk spans (context + removed lines). Use 0 for pure insertion at a position.',
  '',
  '### Line prefixes (MANDATORY — every line after the header needs exactly one):',
  '- ` ` (one space) — context line: must match the file **character-for-character** (same indentation, same content). Copy-paste from `<read>` output.',
  '- `-` — line to remove.',
  '- `+` — line to add.',
  '',
  '### Rules:',
  '- Copy content from `<read>` output verbatim for `-` and ` ` lines. Preserve exact indentation.',
  '- Include 1-2 context lines (` ` prefix) around changes to anchor the position.',
  '- Multiple hunks in one `<edit>` block are allowed. List them top-down.',
  '- After editing, run `<format path="file.ts"/>` to verify syntax. Fix ALL errors before `<end>`.',
  '- If edit fails with "content mismatch", `<read>` the file again and retry with correct line numbers.',
  '- NEVER generate code with syntax errors: unmatched braces, missing semicolons, broken imports, or incomplete statements.',
  '',
  '### Example (illustrative — do NOT copy):',
  '```',
  '<edit path="src/app.ts">',
  '@@ -5,3 @@',
  ' import { foo } from "./foo";',
  '-import { old } from "./old";',
  '+import { replacement } from "./new";',
  ' ',
  '@@ -15,3 @@',
  '-  const name = "old";',
  '-  const value = 42;',
  '-  return { name, value };',
  '+  const name = "new";',
  '+  const value = 100;',
  '+  return { name, value, extra: true };',
  '</edit>',
  '```',
  '',
  '## Write — `<write path="src/file.ts">full file content</write>`',
  'Use for new files or when editing would require replacing most of the file. Prefer `<edit>` for small changes.',
] as const;
